### ISSUE TITLE
切换侧边栏

### ISSUE THREAD

**Issue by imaxing** [taylorchen709/vue-admin#104]
![2018-02-07 17 08 59](https://user-images.githubusercontent.com/26427785/35907711-af40ba18-0c29-11e8-95e9-ff36f2fb49e4.png)

**Comment by zhangchao1088** [comment]
+1

**Comment by 877927262** [comment]
拷贝楼下的代码，解决
Home.vue

.menu-expanded {
  flex: 0 0 180px;
  width: 180px;
  .el-menu {
    width: 100% !important;
  }
  .el-submenu .el-menu-item {
    min-width: 0px !important;
  }
}

**Comment by xingxiangchao** [comment]
.menu-expanded {
  flex: 0 0 230px;
  width: 230px;
  .el-menu {
    width: 100% !important;
  }
  .el-submenu .el-menu-item {
    min-width: 0px !important;
  }
}

**Comment by alex-0407** [comment]
你可以参考我这个项目，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
@imaxing @877927262

**Comment by xushunyan** [comment]
v-show改成v-if 有效
