### ISSUE TITLE
可否升级下版本

### ISSUE THREAD

**Issue by wodliwu** [taylorchen709/vue-admin#105]
作者可否升级下package.json版本， 里面很多都过时不维护了，比如element ui 1.X

**Comment by blanklin030** [comment]
@mailxining 
使用npm update命令可以查看到所有需要更新版本
但是每次都要改下package.js中的版本号为最新才能够更新，太麻烦，没什么用处
可以安装高效升级插件npm-check-updates
npm install -g npm-check-updates
安装之后使用npm-check-updates查看最新的版本
ncu是命令的缩写，也可以用
如果有列出来说明有些包需要升级，这时候我们使用ncu -a就可以全部升级了

**Comment by alex-0407** [comment]
你可以参考我这个项目，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
@mailxining

**Comment by BruceChoo7** [comment]
> 你可以参考我这个项目，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
> @mailxining

请问你的是有更新的版本吗？
