### ISSUE TITLE
uncaught syntaxError: unexpected token <

### ISSUE THREAD

**Issue by superheizai** [taylorchen709/vue-admin#106]
代码打包之后，把dist目录拷贝发布到nginx。启动nginx，访问对应地址，console控制台会输出这个错误，分别在manifest.xxxx.js,vendor.xxxx.js and app.xxxx.js

**Comment by Heimo-He** [comment]
同样有这个问题，请问解决了么

**Comment by Heimo-He** [comment]
build/webpack.base.conf.js

下图红框部分修改下

![image](https://user-images.githubusercontent.com/26212318/38290889-e8f96b44-380f-11e8-9d26-eedcdc3bdf10.png)
