### ISSUE TITLE
版本太低了 ，无法运行

### ISSUE THREAD

**Issue by transient-ad** [taylorchen709/vue-admin#109]
无法运行demo。。

**Comment by carolcoral** [comment]
不，其实是兼容8.x的，只是需要安装sass才行npm install sass

**Comment by alex-0407** [comment]
你可以参考我这个项目，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
@transient-ad @carolcoral

**Comment by john-xia** [comment]
> 你可以参考我这个项目，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
> @transient-ad @carolcoral

能加你QQ or 微信学习下吗

**Comment by iamjwe** [comment]
我更新了这个项目：
参考博客https://blog.csdn.net/jw2268136570/article/details/88673662
参考GitHub：https://github.com/iamjwe/vue-admin
