### ISSUE TITLE
左侧菜单距离左边距不齐

### ISSUE THREAD

**Issue by xuyangxy** [taylorchen709/vue-admin#110]
![image](https://user-images.githubusercontent.com/17880796/39409188-2e02c88e-4c15-11e8-852e-56e14015a537.png)

**Comment by alex-0407** [comment]
你可以参考我这个项目，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace

**Comment by zerogzs** [comment]
Home.vue页面中添加css
`.el-submenu [class^=el-icon-] {
            text-align: left !important;
        }`

**Comment by xuyangxy** [comment]
@zerogzs  好的   感谢
