### ISSUE TITLE
最新的commit是一年之前了，请问一下作者还在继续更新这个项目吗

### ISSUE THREAD

**Issue by hushenao** [taylorchen709/vue-admin#112]

**Comment by alex-0407** [comment]
我也是根据这个项目做的，你可以参考https://github.com/alex-0407/vue2-admin-grace

**Comment by iamjwe** [comment]
我更新了这个项目：
参考博客https://blog.csdn.net/jw2268136570/article/details/88673662
参考GitHub：https://github.com/iamjwe/vue-admin
