### ISSUE TITLE
无法运行，Error: listen EADDRINUSE :::8001

### ISSUE THREAD

**Issue by DavidMGT** [taylorchen709/vue-admin#116]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8089
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at Function.listen (/Users/aochuang01/Vue Demo/node-elm-master/node_modules/express/lib/application.js:618:24)
我尝试修改了多次端口，都是同样的错误

**Comment by DavidMGT** [comment]
mysqld       99         _mysql   13u  IPv6 0xeffd3b69cf42551d      0t0    TCP *:3306 (LISTEN)
QQ          393     aochuang01   33u  IPv4 0xeffd3b69d3843645      0t0    TCP localhost:4300 (LISTEN)
QQ          393     aochuang01   35u  IPv4 0xeffd3b69dd6ef265      0t0    TCP localhost:4301 (LISTEN)
rapportd    412     aochuang01    3u  IPv4 0xeffd3b69d2bb0fa5      0t0    TCP *:49170 (LISTEN)
rapportd    412     aochuang01    4u  IPv6 0xeffd3b69cf425add      0t0    TCP *:49170 (LISTEN)
webstorm    568     aochuang01   24u  IPv4 0xeffd3b69d6b7abc5      0t0    TCP localhost:63342 (LISTEN)
webstorm    568     aochuang01  143u  IPv4 0xeffd3b69d6c7dbc5      0t0    TCP localhost:6942 (LISTEN)
Adobe\x20   573     aochuang01    7u  IPv4 0xeffd3b69d6c7d265      0t0    TCP localhost:15292 (LISTEN)
cupsd      5163           root    5u  IPv6 0xeffd3b69cf426c1d      0t0    TCP localhost:631 (LISTEN)
cupsd      5163           root    6u  IPv4 0xeffd3b69d6c68905      0t0    TCP localhost:631 (LISTEN)
mongod    15159     aochuang01   10u  IPv4 0xeffd3b69dd70cfa5      0t0    TCP localhost:27017 (LISTEN)
node      15678     aochuang01   14u  IPv6 0xeffd3b69cf42609d      0t0    TCP *:8001 (LISTEN)
node      15812     aochuang01   15u  IPv6 0xeffd3b69cf42665d      0t0    TCP *:8089 (LISTEN)

**Comment by alex-0407** [comment]
最新版看过来：https://github.com/alex-0407/vue2-admin-grace
