### ISSUE TITLE
缺少ESLint对代码的约束

### ISSUE THREAD

**Issue by yay00yay** [taylorchen709/vue-admin#117]
你的这个demo非常好！
我花了一天把自己的需求换上去了。
只是最后build出来的dist file不能在express server下直接serve。
记得是什么 “undefined token <”的错误。
后来我花了一晚上用ESLint把code改了一便，才好了。

**Comment by iamjwe** [comment]
我更新了这个项目：
参考博客https://blog.csdn.net/jw2268136570/article/details/88673662
参考GitHub：https://github.com/iamjwe/vue-admin

**Comment by alex-0407** [comment]
最新版看过来：https://github.com/alex-0407/vue2-admin-grace
