### ISSUE TITLE
执行npm install出问题

### ISSUE THREAD

**Issue by mamba-in** [taylorchen709/vue-admin#119]
![_20181201195536](https://user-images.githubusercontent.com/21197600/49327977-98648900-f5a3-11e8-9a1e-c18a9cf817d6.png)

**Comment by lixiusen** [comment]
cnpm install

**Comment by mamba-in** [comment]
好的，多谢

发送自 Windows 10 版邮件应用

发件人: lixiusen
发送时间: 2018年12月13日 12:30
收件人: taylorchen709/vue-admin
抄送: Wong_24; Author
主题: Re: [taylorchen709/vue-admin] 执行npm install出问题 (#119)

cnpm install

**Comment by iamjwe** [comment]
我更新了这个项目：
参考博客https://blog.csdn.net/jw2268136570/article/details/88673662
参考GitHub：https://github.com/iamjwe/vue-admin

**Comment by alex-0407** [comment]
最新版看过来：https://github.com/alex-0407/vue2-admin-grace
