### ISSUE TITLE
框架支持左侧菜单收齐更完美了！

### ISSUE THREAD

**Issue by qmdx** [taylorchen709/vue-admin#25]
框架支持左侧菜单收齐更完美了！

**Comment by uruir** [comment]
@qmdx 作者用了 element 主题，而 element 并不支持收拢边栏，请看 http://element.eleme.io/#/zh-CN/component/menu

**Comment by uruir** [comment]
@qmdx 可以修改 content-container 样式里的 left 值实现显示/隐藏边栏，已实现

**Comment by sofire** [comment]
支持

**Comment by taylorchen709** [comment]
已支持
