### ISSUE TITLE
您好，我在npm run dev之后，总是报错1% is not a valid application ？

### ISSUE THREAD

**Issue by LXMin** [taylorchen709/vue-admin#27]
install之后直接run的话，就会报这个错误，如下面的图：
![1](https://cloud.githubusercontent.com/assets/20547898/23540782/5d48a4ae-001e-11e7-88f1-c1e6470d233e.png)

**Comment by taylorchen709** [comment]
删除node_modules，重新npm install试试

**Comment by LXMin** [comment]
删了也还是不行，提示我一直在下载一个东西，之后就是下载失败，您可以看下下面的图。您的电脑是不是32的位的电脑呀？
![1](https://cloud.githubusercontent.com/assets/20547898/23685913/94678d8a-03e1-11e7-9942-1efdbae7dd19.png)

**Comment by tkylin** [comment]
下载node-sass失败解决方法:
可能由于网络问题下载win32-x64-48_binding.node失败,
去https://github.com/sass/node-sass/releases 这里下载需要的版本
下载后放到某目录项目依赖的目录即可
