### ISSUE TITLE
问一个小白的问题，怎么将这个东西嵌入到java web工程当中

### ISSUE THREAD

**Issue by yaakua** [taylorchen709/vue-admin#33]
如题，我想直接将代码嵌入到java web工程当中当静态页面开发，然后通过ajax方式获取后端的接口数据。
但是看示例这个是通过一个独立的服务端运行起来供浏览器访问的，这样我不是要启动两个程序了？
有没有办法在传统那种java web里面直接修改html\js文件，就可以运行起来？

**Comment by kevinlinit** [comment]
我也在做这个，同问

**Comment by Youjingyu** [comment]
npm run build，会生成dist文件夹，dist文件夹里就是你需要的静态文件

**Comment by DragonBUAA** [comment]
开发环境配置proxyTable将接口转发，生产环境配置nginx提供dist入口和接口转发，这里有写https://zhuanlan.zhihu.com/p/27870472

**Comment by cdoer** [comment]
问题是代码都是压缩的并且  混淆了 ，  如何build为开发版代码？
