### ISSUE TITLE
构建之后index.html css js引用路径错误

### ISSUE THREAD

**Issue by sxhjlzl** [taylorchen709/vue-admin#36]
构建后index.html   引用路径
href=/vue-admin/static/css/app.ef2fcc366e180adb09000e69537d6aeb.css

正确路径
href=./static/css/app.ef2fcc366e180adb09000e69537d6aeb.css

**Comment by cssxn** [comment]
@sxhjlzl 

修改**assetsPublicPath**，在**config**目录下的**index.js**
