### ISSUE TITLE
关于ajax跨域访问的问题,返回的响应头需要Access-Control-Allow-Origin怎么解决？

### ISSUE THREAD

**Issue by kevinlinit** [taylorchen709/vue-admin#37]
如题：在项目中我修改了api/api.js的地址为公司项目接口的地址，也是通过axios发送ajax请求，和后端调试能够连通但返回时出错，就是http那个协议需要带Access-Control-Allow-Origin的响应头。该如何解决？

**Comment by doudouma** [comment]
需要开发设置下
Access-Control-Allow-Origin: *
所有人访问，或者可以写你的ip。就是只有这个ip范文

**Comment by 953133667** [comment]
需要后台在响应头中配置一下，可以百度一下 CORS （跨域资源共享），希望能帮到你
