### ISSUE TITLE
如果需要做一个权限菜单，根据不同的用户，登陆后有不同的菜单选项该怎么做？

### ISSUE THREAD

**Issue by kevinlinit** [taylorchen709/vue-admin#41]

**Comment by zhonggedan** [comment]
addroutes

**Comment by ipengyo** [comment]
1、给你的所有的router 添加一个 mate自定义数据 里面存储的这个router所需的 权限
2、当用户登录后 从服务器获取到用户的权限
3、beforeEach 时 去动态的 计算出 当前用户可以访问哪些router 
4、 根据计算出的router 列表，然后 router.addRoutes

**Comment by tsungche** [comment]
想了一個禮拜還是做不出來，大大是否再詳細如何做到做一个权限菜单，根据不同的用户

**Comment by iamlucchen** [comment]
我也是个小白，我也不懂，试验了一下可以简单这么改...我是这么弄的
1.user.js加一个type字段:
import Mock from 'mockjs';
const LoginUsers = [
  {
    id: 1,
    username: 'admin',
    password: '123456',
    type:3,
    avatar: '/static/aac.jpg',
    name: 'AAC_Developer'
  },{
    id: 1,
    username: 'lulu',
    password: '123456',
    type:1,
    // avatar: 'https://raw.githubusercontent.com/taylorchen709/markdown-images/master/vueadmin/user.png',
    avatar: '/static/person.jpg',
    name: 'dsadas'
  }
];

2.routes.js加入一个permission字段，定义权限级别
    {
        path: '/',
        component: Home,
        name: '',
        iconCls: 'fa fa-address-card',
        leaf: true,//只有一个节点
        permission:1,
        hidden:true,
        children: [
            { path: '/connect', component: connect, name: '帮助与支持'},
        ]
    }, 
3.Home.vue 导航栏增加如下判定
<el-submenu :index="index+''" v-if="!item.leaf && sysUserType>=item.permission">
js里面获取也改一下：
		mounted() {
			var user = sessionStorage.getItem('user');
			// console.log(user);
			if (user) {
				user = JSON.parse(user);
				this.sysUserName = user.name || '';
				this.sysUserAvatar = user.avatar || '';
				this.sysUserType = user.type || '';
			}
		}
4.相应的page也增加判定，比如<div v-if="sysUserType>=2">

**Comment by iamlucchen** [comment]
我也是个小白，我也不懂，试验了一下可以简单这么改...我是这么弄的
1.user.js加一个type字段:
import Mock from 'mockjs';
const LoginUsers = [
{
id: 1,
username: 'admin',
password: '123456',
type:3,
avatar: '/static/aac.jpg',
name: 'AAC_Developer'
},{
id: 1,
username: 'lulu',
password: '123456',
type:1,
// avatar: 'https://raw.githubusercontent.com/taylorchen709/markdown-images/master/vueadmin/user.png',
avatar: '/static/person.jpg',
name: 'dsadas'
}
];

2.routes.js加入一个permission字段，定义权限级别
{
path: '/',
component: Home,
name: '',
iconCls: 'fa fa-address-card',
leaf: true,//只有一个节点
permission:1,
hidden:true,
children: [
{ path: '/connect', component: connect, name: '帮助与支持'},
]
},
3.Home.vue 导航栏增加如下判定
《el-submenu :index="index+''" v-if="!item.leaf && sysUserType>=item.permission"》

js里面获取也改一下：
mounted() {
var user = sessionStorage.getItem('user');
// console.log(user);
if (user) {
user = JSON.parse(user);
this.sysUserName = user.name || '';
this.sysUserAvatar = user.avatar || '';
this.sysUserType = user.type || '';
}
}
4.相应的page也增加判定，比如
《div v-if="sysUserType>=2"》
