### ISSUE TITLE
vendor.js过大的问题

### ISSUE THREAD

**Issue by HaoKown** [taylorchen709/vue-admin#44]
您的在线演示地址，vendor.js的大小为480k，我在本地build您的项目后生成的vendor.js有1.4MB，不知道为什么？有什么方法可以减少编译后打包的js库大小吗？十分感谢

**Comment by taylorchen709** [comment]
可以将config/index.js build.productionSourceMap设置为false

**Comment by HaoKown** [comment]
按照您的设置并没有解决呀,还有什么方法吗

**Comment by qq5050595531** [comment]
适当把握一下插件引入的合理性和适用性。对于一下些用得不太频繁组件的 require.ensure()引入看看。

**Comment by ohhoney1** [comment]
作者说的是一个方法，线上环境可以关闭Source Map。
对于大的组件，可以按需引入。
另外，配置路由的时候可以采用懒加载的模式：
[vue-router懒加载](http://router.vuejs.org/zh-cn/advanced/lazy-loading.html)
