### ISSUE TITLE
build 之后运行压缩后的代码 图片路径和字体路径不对

### ISSUE THREAD

**Issue by xiaomaoaaa** [taylorchen709/vue-admin#47]
build 之后运行压缩后的代码 图片路径和字体路径不对！
字体文件和背景图片在css中引用的路径不对

**Comment by taylorchen709** [comment]
修改config/index.js build.assetsPublicPath

**Comment by semmy2010** [comment]
改这个也不行的，相对路径不正确

**Comment by ohhoney1** [comment]
/build/webpack.base.conf.js文件里，修改图片的大小限制或者直接去掉限制
`{
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },`

**Comment by ohhoney1** [comment]
应该是图片太大，转不了base64，导致路径错误。你试一下是不是这个问题。
