### ISSUE TITLE
路由路径中为什么总会有个“#”

### ISSUE THREAD

**Issue by rebornvip** [taylorchen709/vue-admin#53]
http://localhost:9999/#/login
http://localhost:9999/#/table

**Comment by qq5050595531** [comment]
理解一下hashhistory和bowserhistory。vue-route可以把#去掉的。

**Comment by wernerm** [comment]
See the documentation about setting the router mode to 'history': https://router.vuejs.org/en/api/options.html#mode

You might also need to adjust the web server configuration: https://router.vuejs.org/en/essentials/history-mode.html
