### ISSUE TITLE
Table不能全选

### ISSUE THREAD

**Issue by heyanlong** [taylorchen709/vue-admin#54]
您好，我运行demo可以全选，但是嵌入到laravel-mix 里面就不能全选了
mix.js('resources/assets/vue/admin/main.js', 'public/js').extract(['vue']);

**Comment by ictx** [comment]
好像跟是否嵌入无关。
全新安装，cnpm install, npm run dev后，发现table中的checkbox故障：
（1）点击全选，无法在界面上选中table中的checkbox，但是触发了 select-change事件，消息表明已经全选；
（2）点击单个checkbox，可以在界面上选中，但是没有触发 select-change事件。
一个月前运行没问题，怀疑是某些依赖跟elementUI有冲突。
不知道怎么排查，请taylor大大有空的时候帮忙看看。

**Comment by alukaka** [comment]
我也遇到了同样的问题

**Comment by alukaka** [comment]
升级element-UI版本就可以了

**Comment by ictx** [comment]
package.json 中 "element-ui": "^1.2.8", 现在安装都是1.2.9，是element-UI的最新版本了。问题依然存在。不妨亲自试试。

**Comment by heyanlong** [comment]
@ictx @alukaka 添加 .babelrc 修复问题
```json
{
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime"],
  "comments": false
}
```

**Comment by ictx** [comment]
@heyanlong 这个配置已经在版本中添加了，不需再单独添加。
出现的问题与这个配置无关。
换一台电脑，或者删除依赖、重新安装，问题就会出现。

**Comment by heyanlong** [comment]
@ictx 是我 laravel-mix 只会读取项目根目录的.babelrc，所以我把你这个配置写到了项目根目录一份，就解决了
