### ISSUE TITLE
大神出一个vue-admin iviewui版本把，感觉 iviewui 精致一点

### ISSUE THREAD

**Issue by qmdx** [taylorchen709/vue-admin#55]
大神出一个vue-admin iviewui版本把，感觉 iviewui 精致一点

https://www.iviewui.com/components/button

**Comment by heyanlong** [comment]
走起。。

**Comment by TonyLuo** [comment]
@qmdx https://github.com/TonyLuo/i-admin
撸了一个iview ui版本的模板，欢迎贡献代码
