### ISSUE TITLE
陈佬，请求解

### ISSUE THREAD

**Issue by hvaggg** [taylorchen709/vue-admin#62]
![Uploading Z]T~D2HH2F{YJO%$7KRS0}K.png…]()
您写的左侧导航栏，我需要这样的效果，我在您写的路由中写了三级路由为什它不显示呢>请指教，有偿也可以！！！谢谢，耽误您时间了
![1498110773 1](https://user-images.githubusercontent.com/25985929/27422390-91e8b4f8-5760-11e7-9cdf-301b73f6e0dc.jpg)

**Comment by hvaggg** [comment]
![z t d2hh2f yjo 7krs0 k](https://user-images.githubusercontent.com/25985929/27422429-b5cce286-5760-11e7-801e-f0ae35971933.png)
这个是需求！！上面的没识别

**Comment by qq5050595531** [comment]
重写导航菜单，导航菜单只到二级分类

**Comment by BrianAguilar** [comment]
@qq5050595531 结合router.js路由文件只需要改造Main.vue这个文件？
