### ISSUE TITLE
为什么第一次加载特别慢，好几分钟才出来登录页面。这个怎么破，求解？

### ISSUE THREAD

**Issue by yangyangwang** [taylorchen709/vue-admin#63]

**Comment by ipengyo** [comment]
这个一定是你的网络原因。
可能是这个网页是放在国外的。

**Comment by yangyangwang** [comment]
不会啊，我就把这个源码下载下来，放在虚拟主机上，跑了起来。去访问登录页面，就要1分多钟才加载出来登录页面，感觉登录页面要去下载什么吗，

**Comment by edwinhuish** [comment]
@yangyangwang 你应该先看看你的环境问题。我这边速度不慢。

另外，如果你是指 ```npm run dev ``` 后的第一次登陆，那是正常的，因为需要编译。

**Comment by yangyangwang** [comment]
@edwinhuish 嗯嗯，明白，谢谢你，我再看看。
