### ISSUE TITLE
跨域请求该在哪里配置？

### ISSUE THREAD

**Issue by mawenge** [taylorchen709/vue-admin#65]
您好，项目启动是在8080端口上面启动的，但是我的里面的接口实在本地另外的环境里面的，比如说8113端口，在哪里配置能够使所有的网络请求都跨到localhost:8113上面呢？

**Comment by DragonBUAA** [comment]
开发环境配置proxyTable将接口转发，生产环境配置nginx提供dist入口和接口转发，这里有写https://zhuanlan.zhihu.com/p/27870472

**Comment by sampsonliu** [comment]
开发环境，要跨域，api.js设置axios.defaults.withCredentials = true，表明请求允许携带cookie，请求的响应端只需设置 
header("Access-Control-Allow-Origin: http://localhost:8080");
header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept");
header("Access-Control-Allow-Credentials: true");
就可以了

**Comment by linya0220** [comment]
这样设置线上好像根本不管用 @sampsonliu

**Comment by alex-0407** [comment]
你可以参考我这个项目，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
生产环境跨越用jsonp或者搭建代理服务器nginx
@mawenge @linya0220 @xueyalong
