### ISSUE TITLE
怎么axios的api.js 看不到network请求？ 邮箱有吗 ，可以交流一下啊？

### ISSUE THREAD

**Issue by vela-security** [taylorchen709/vue-admin#67]

**Comment by winkeylucky** [comment]
mock + axios-mock-adapter; 本地数据模拟 + 请求拦截；

**Comment by alex-0407** [comment]
你可以参考我这个项目，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
@MrNsfocus

**Comment by sxlisme** [comment]
var **instance** = axios.create({ headers: {'content-type': 'application/x-www-form-urlencoded'} });

 export const requestLogin = params => { return **instance**.post(`/login`, params).then(res => res.data).catch((err)=>{
       console.log(err);
  })};
