### ISSUE TITLE
请教几个问题，还望大大回复n(*≧▽≦*)n

### ISSUE THREAD

**Issue by Chuyue0** [taylorchen709/vue-admin#68]
1.初次用谷歌浏览器登录时加载有点慢；2.请问一下这些数据都是自己模拟的吗？3.右上角的用户那一块多次点击感觉有问题；4.如果需要用vue做cms后台管理还需要处理一些什么，目前对路由这一块不是特别熟悉？5.进入到列表页时，向后台请求数据怎么做好分页处理（返回所有数据）；6.clone下来可以直接在本地运行吗？
O(∩_∩)O谢谢

**Comment by liangxin123** [comment]
进入到列表页时，向后台请求数据怎么做好分页处理（返回所有数据）
我也想问这个问题，怎么和后台交互的，后台在哪处理请求的？

**Comment by Chuyue0** [comment]
唔，大佬许久都没有回复，我也是求问者

**Comment by alex-0407** [comment]
你可以参考我这个项目，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
@Chuyue0 @liangxin123 @

**Comment by Chuyue0** [comment]
好的，已经收到您的邮件了，谢谢。
