### ISSUE TITLE
bug：左侧菜单收起按钮(class="tools") 点击之后再展开，宽度未还原

### ISSUE THREAD

**Issue by ajaxQWER** [taylorchen709/vue-admin#70]
左侧菜单收起之后再展开，el-menu的宽度还是为收起的宽度，未改为100%，在哪里修改的？

**Comment by ajaxQWER** [comment]
已发现问题，把el-menu上的v-show改成v-if就行了

**Comment by wonderchief** [comment]
v-if也不是处理得很好，我改了一下用el-menu :style="{display: collapsed ? 'none' : 'inherit'}"代替v-if或者v-show渲染速度更快

**Comment by weijun876** [comment]
v-if是好了，但是第一个菜单好像和下面的不对其

**Comment by ZHENGGEGE** [comment]
@wonderchief 这样折叠动画好多了 v-if有卡顿
