### ISSUE TITLE
垂直菜单显示空白

### ISSUE THREAD

**Issue by zhangjingjing2020** [taylorchen709/vue-admin#73]
![wx20170803-105821](https://user-images.githubusercontent.com/12322141/28904052-e3ca09ca-783a-11e7-8a4d-5cce490e76db.png)
默认是正常的，点击一次后显示不正常

**Comment by zhangjingjing2020** [comment]
![wx20170803-110313](https://user-images.githubusercontent.com/12322141/28904129-617ba450-783b-11e7-97b4-9189ff7a0c5c.png)
ul的行内样式会多一个64px的宽度

**Comment by 274776500** [comment]
同遇到楼上的问题，demo的在线演示一切正常，但是download到本地跑起来就有这个bug，点击tools小图标后ul标签上自动添加了一个width为64px的宽度，目前未发现如何解决。

**Comment by zhangjingjing2020** [comment]
@274776500 大概知道是element升级的原因了，有一个简单的方法就是把package.json中的element-ui依赖指定为1.2.8(即：去掉^1.2.8前面的^符号)，然后重新安装。

**Comment by 274776500** [comment]
@zhangjingjing2020 非常感谢你的解答，确实解决了这个问题，但是我有些不太明白，^1.2.8和1.2.8有什么区别吗，是把element依赖包换成老版本的意思吗，那以后的开发还不能使用element的最新版本吗？

**Comment by fqybzhangji** [comment]
Please refer to https://github.com/taylorchen709/vue-admin/issues/70

**Comment by zhangjingjing2020** [comment]
@fqybzhangji 3Q~
