### ISSUE TITLE
注释掉mock 调用，那在api.js　文件中　需要指定下base url 吗？

### ISSUE THREAD

**Issue by leeyongda** [taylorchen709/vue-admin#77]
import axios from 'axios';
let base = '';　　// 这里是否需要指定一个请求根地址？
export const requestLogin = params => { return axios.post(`${base}/login`, params).then(res => res.data); };

**Comment by umeitime** [comment]
怎么注释mock的？

**Comment by alex-0407** [comment]
你可以参考我这个项目，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
@leeyongda @umeitime
