### ISSUE TITLE
在linux下无法跑起来项目

### ISSUE THREAD

**Issue by hym1884603** [taylorchen709/vue-admin#8]
⠧ Installing inherits@^2.0.1platform unsupported webpack@1.14.0 › watchpack@0.2.9 › chokidar@1.6.1 › fsevents@1.0.15 Package require os(darwin) not compatible with your platform(linux)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(linux)

**Comment by sampsonliu** [comment]
我照着做都可以的
