### ISSUE TITLE
侧边栏两级导航怎么写的？

### ISSUE THREAD

**Issue by sampsonliu** [taylorchen709/vue-admin#80]
{
        path: '/',
        component: Home,
        name: '导航二',
        iconCls: 'fa fa-id-card-o',
        children: [
            { path: '/page4', component: Page4, name: '页面4' },
            {
                path: '/dd/',
                name: '导航2-1',
                iconCls: 'fa fa-id-card-o',
                children: [
                    {path: '/page5', component: Page5, name: '页面5'}
                ]
            }
        ]
    },
好像不是这么写的

**Comment by linya0220** [comment]
这个案例不支持二级的，二级自己重新编写个组件替换即可 @sampsonliu
