### ISSUE TITLE
编译发布版本的时候字体文件引入不对

### ISSUE THREAD

**Issue by ysjsgzq** [taylorchen709/vue-admin#81]
项目刚下载下来的时候，我直接npm run build ，生成的页面，引入js，和css是使用的绝对路径。然后我就把config目录下index.js 里面build 的assetsPublicPath: './',改成这样了。这样编译以后css和js引用路径对了。但是字体文件的路径不对。前端小白。还望大神指教

**Comment by sampsonliu** [comment]
为什么一定要使用绝对路径呢？相对路径不好么，
![b828f2de-5ff9-47ba-825b-7b77b40772c3](https://user-images.githubusercontent.com/15682051/30313804-32ff1d5e-97d1-11e7-8b53-385045b19e5b.png)
![071c887b-a884-419e-9e31-0d548c15a7c3](https://user-images.githubusercontent.com/15682051/30313812-3c0ba5fc-97d1-11e7-8137-fcd11d3b07aa.png)

**Comment by alex-0407** [comment]
你可以参考我这个项目，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
@ysjsgzq
