### ISSUE TITLE
急急急，列表上的編輯按鈕 ckeditor bug 

### ISSUE THREAD

**Issue by tsungche** [taylorchen709/vue-admin#83]
列表上的編輯按鈕=> editForm 的物件裡面有一個 ckeditor editForm.host_decs,

發現 點擊 編輯時=> row.host_decs 無法替換掉 editForm.host_decs 的值，點擊編輯看到的editor裡面的值永遠都是第一筆，求大大 解題。

我的ckeditor 是一個 components

```
 <el-tab-pane label="內容資訊" name="contentInformation">
                     <ckeditor :config="config" v-model="editForm.host_desc"></ckeditor>
</el-tab-pane>
```

**Comment by alex-0407** [comment]
你可以参考我这个项目，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
@tsungche
