### ISSUE TITLE
数据上的问题

### ISSUE THREAD

**Issue by DistantDream** [taylorchen709/vue-admin#87]
编辑和新增的时候都有年龄以及出生日期的输入框，然而却可以随意输入，出生日期跟年龄不对应。。应如何将此关联。也应该算是一个bug吧

**Comment by DistantDream** [comment]
新增后的数据在用户重新登入后却没有，只在不退出用户的时候可查。然而删除却可以

**Comment by rolitter** [comment]
这是 ElemeFE官方的库,这个是参照官方的修改的
https://github.com/ElemeFE/element-dashboard/
