### ISSUE TITLE
伸缩左侧导航有问题，收回来时候导航显示不全，试了多个版本，是我本地环境问题吗

### ISSUE THREAD

**Issue by weijun876** [taylorchen709/vue-admin#88]

**Comment by bangxingni** [comment]
.el-menu {
        width: 100% !important;
      }
      .el-submenu .el-menu-item {
        min-width: 0px !important;
      }
手动解决。

**Comment by true1023** [comment]
把导航菜单和导航菜单折叠后 这两个的v-show 换成 v-if和v-else
是ui-element的版本问题，也可以把ui-element的版本换成1.2.8，不过这样的话Table页面的checkbox全选功能又会出问题

**Comment by JustZzzxf** [comment]
2楼方法也有问题的,这样收起展开后 鼠标悬停时展开隐藏子菜单宽度有问题。可以在展开菜单上加上样式class="el-menu-expand", 然后下边样式文件中写明
`.el-menu-expand {
					width: 100% !important;
				}`
亲测有效

**Comment by bangxingni** [comment]
.menu-expanded {
      flex: 0 0 180px;
      width: 180px;
      .el-menu {
        width: 100% !important;
      }
      .el-submenu .el-menu-item {
        min-width: 0px !important;
      }
    }
忘记贴全了....

**Comment by hsir05** [comment]
@bangxingni 用你的方法解决了 ok 感谢

**Comment by alex-0407** [comment]
你可以参考我这个项目，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
@weijun876

**Comment by zhurenyangxiong** [comment]
> ```
> .menu-expanded {
>   flex: 0 0 180px;
>   width: 180px;
>   .el-menu {
>     width: 100% !important;
>   }
>   .el-submenu .el-menu-item {
>     min-width: 0px !important;
>   }
> }
> ```
> 忘记贴全了....

这个样式写在home.vue文件中的style里面么？
