### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by tzfly** [taylorchen709/vue-admin#89]
Module parse failed: C:\Users\user\WebstormProjects\vue-admin\node_modules\element-ui\packages\scrollbar\src\main.js Unexpected token (65:6)
You may need an appropriate loader to handle this file type.
You may need an appropriate loader to handle this file type.
|     }, this.$slots.default);
|     const wrap = (
|       <div
|         ref="wrap"
|         style={ style }
请问这个是什么原因呢？谢谢

**Comment by linya0220** [comment]
你这是react写多了吧。。。@tzfly

**Comment by Aetherus** [comment]
这个问题貌似已经是Element UI的顽疾了。Element UI官方库已经收到很多这个issue的票子了，但就是不改。不是由于所谓的“提问格式不符合规定”，就是“请参照quickstart”。

**Comment by xvnian** [comment]
https://github.com/ElemeFE/element/issues/14379

**Comment by Zeus-Iqd** [comment]
@xvnian thankyou
