### ISSUE TITLE
url 不正常

### ISSUE THREAD

**Issue by suiwenfeng** [taylorchen709/vue-admin#90]
https://taylorchen709.github.io/vue-admin/#/login

这里面的#/ 从哪里来的。。

**Comment by rolitter** [comment]
这种情况是因为在入口js文件中，如果你不更改设置的话，vue会默认使用hash模式，该模式下会将路径格式化为 # 开头。
如果需要美化路径，可以更改模式为 history ：

![20170809133701458](https://user-images.githubusercontent.com/27326998/32434246-7547ea20-c318-11e7-8527-bd5bf318c4d2.png)


vue-router官方文档：https://router.vuejs.org/zh-cn/essentials/history-mode.html
