### ISSUE TITLE
请教一下如何 请求后台数据 

### ISSUE THREAD

**Issue by AncestorDragon** [taylorchen709/vue-admin#92]
我看了这个框架 ，现在的数据都是user.js 随机生成的 ，请问 如何去请求后台服务接口的数据 ，我参考了网上很多例子，但是就是请求 不到，感觉请求都没发出去 ，能不能给我个demo例子，谢谢了。我主要做后端的，现在想学习套用你这个前端UI的框架，拜托了

**Comment by weijun876** [comment]
我把USER TABLE的API转成DJANGO RESTFUL API 一直请求不到报404啊 不知道为什么

**Comment by Laann** [comment]
我也是  用axios请求不到数据  一直报404错误

**Comment by bay1** [comment]
前天写了一个flask做后端的，或许能给些帮助
[vue-admin-flask-example](https://github.com/bay1/vue-admin-flask-example)

**Comment by yqh708** [comment]
@bay1 大神，请问一下，我不需要mock的模拟数据，我要怎么请求api获取到后台 的数据呢？我需要重新写一个方法吗？我看了您的项目，还是不太明白，请求指点指点

**Comment by bay1** [comment]
@yqh708 首先你需要注释掉mock引入部分，然后你参照我的那个例子里api的样式写自己的请求，那些具体的代码你可以在vue-admin-flask-example/src/api/api.js找到

**Comment by yqh708** [comment]
@bay1 可以了，谢谢。要把main.js中的mock引入和Mock.bootstrap();注释就可以了

**Comment by miloshu** [comment]
需要把整个mock文件夹删掉吗?  那mock文件夹里面的mock.js 没有之后 再用后台服务接口会不会有影响??? 新手 求怎么调用自己后台的接口 而不用您这个项目的mock

**Comment by Laann** [comment]
@miloshu  首先你要屏蔽掉这个demo的请求模拟数据的方法，参考6楼的做法。  屏蔽了之后，就可以用ajax调自己后台接口了。  这个demo用的v-aiosx插件来模拟获取的后台数据。  有一个讨巧的办法，不用屏蔽或者删除掉其他东西，你改用v-resource来请求ajax也可以，我试过

**Comment by miloshu** [comment]
@Laann  resource 已经过时了 我用的是axios, 就是要把main.js的 import Mock from './mock'
Mock.bootstrap()  注释 然后删掉mock文件夹就可以吗?  我看到mock.js文件夹里面的mock.js有些很多请求逻辑  删掉会不会有影响

**Comment by miloshu** [comment]
删除所有的mock之后  然后直接修改API里面的api.js文件替换成自己的接口就可以了是吗

**Comment by Laann** [comment]
@miloshu 是的  api.js是他自己封装的，你不用也可以

**Comment by alex-0407** [comment]
你可以参考我这个项目，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
@AncestorDragon @weijun876 @Laann @bay1 @yqh708

**Comment by BrianAguilar** [comment]
@alex-0407 你好这个header怎么去固定，不滚动，实际项目中一个厂字形，如何改造Home.vue左边把二级菜单改成三级菜单
