### ISSUE TITLE
代码拉下来，cpm run dev的时候报错

### ISSUE THREAD

**Issue by daiyanxia** [taylorchen709/vue-admin#93]
![image](https://user-images.githubusercontent.com/29750417/33049082-5ad1b05e-ce99-11e7-9e91-027810f30c8c.png)

**Comment by daiyanxia** [comment]
抱歉问题已经解决

**Comment by jpj19921015** [comment]
怎么解决的啊

**Comment by jpj19921015** [comment]
哦，改个端口号，顶部那个隐藏显示的按钮，使左边隐藏后再显示就成空白了

**Comment by alex-0407** [comment]
你可以参考我这个项目，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
@jpj19921015

**Comment by john-xia** [comment]
> 怎么解决的啊

怎么解决的啊

**Comment by john-xia** [comment]
我也是报这个错

**Comment by summer123123123** [comment]
请问怎么解决这个问题
