### ISSUE TITLE
可以后台jsp输出变量到html吗？

### ISSUE THREAD

**Issue by weituotian** [taylorchen709/vue-admin#96]
有一个页面，要调很多接口，
但是在spring，用model保存好所有变量，到jsp就能直接用，
那vue打包后的html怎么整合到jsp中？

**Comment by MinosIE** [comment]
这种单页面应用，一般都是前后端分离的，分离之后，前后端各自关注自己的东西就好了。不明白楼主为什么又要把代码混在一起

**Comment by weituotian** [comment]
@MinosIE 就是不做jsp了，全部返回json?

**Comment by MinosIE** [comment]
是的 后端提供接口，前端发送http请求数据

**Comment by weituotian** [comment]
@MinosIE 
看样子都是这样做的。

**Comment by dnvodc** [comment]
springboot 专注于 webservice,vue专注于 ui

**Comment by ranji1221** [comment]
当然可以

在 2019-06-27 14:17:20，"dnvodc" <notifications@github.com> 写道：


springboot 专注于 webservice,vue专注于 ui
