### ISSUE TITLE
左侧菜单展示不全问题

### ISSUE THREAD

**Issue by MinosIE** [taylorchen709/vue-admin#97]
node v - 8.2.1 详细见以下动图：
![bug](https://user-images.githubusercontent.com/7985586/34702711-311b2dbe-f52a-11e7-9c2b-8faf6b509a4c.gif)
想请教下大神，64px的行内样式是在哪里添加的

**Comment by lenzeon** [comment]
可参考 issue #88

**Comment by lsqswl** [comment]
我也是遇到这个问题。还有一个问题是npm run build之后，dist里面的index.html打开是空的。

**Comment by jqrrgmvtk** [comment]
@lsqswl 你的这两个问题解决了没？？谢谢

**Comment by alex-0407** [comment]
你可以参考我这个项目，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
@MinosIE @lsqswl @jqrrgmvtk @blanklin030

**Comment by MinosIE** [comment]
@blanklin030 感谢 小姐姐

**Comment by hanluner** [comment]
@blanklin030 这样加也不行

**Comment by hanluner** [comment]
@MinosIE 你怎么解决的？
