### ISSUE TITLE
左部菜单字体图标错位

### ISSUE THREAD

**Issue by visket** [taylorchen709/vue-admin#98]
src-->routes.js
左部菜单第一个菜单的字体图标跟下面的错位了，在第31行：“导航一”，iconCls: 'el-icon-message'。
可直接更改成'fa el-icon-message'。

然后还发现一个问题，Home.vue文件里，菜单收起的部分<li>跟<ul>嵌套报错，因为我已经改过，行数不对了，在注释之后。

**Comment by alex-0407** [comment]
你可以参考我这个项目，这个问题已解决，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
@visket

**Comment by visket** [comment]
我已经改啦，花了点时间在这套基础上完善了自己项目需要的组件
