### ISSUE TITLE
关于请求ajax的问题 求大神解答

### ISSUE THREAD

**Issue by Laann** [taylorchen709/vue-admin#99]
用axios怎么也请求不到数据，一直报404错误    打开network也看不到http请求的内容  求大神解答啊

**Comment by MinosIE** [comment]
看一下 src/mock/mock.js
项目使用了 axios-mock-adapter 这个插件来模拟假数据的。
你可以了解一下

**Comment by alex-0407** [comment]
你可以参考我这个项目，jsonp跨域版本和axios都有，也是这个项目基础上做的https://github.com/alex-0407/vue2-admin-grace
@Laann @MinosIE

**Comment by chen152009** [comment]
main.js
 // import Mock from './mock'
// Mock.bootstrap();
